// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto.proto

It has these top-level messages:
	InfoReq
	InfoRes
	CreateChatReq
	CreateChatRes
	SendMessageReq
	SendMessageRes
	Chatter
	Chat
	Message
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type InfoReq struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *InfoReq) Reset()                    { *m = InfoReq{} }
func (m *InfoReq) String() string            { return proto1.CompactTextString(m) }
func (*InfoReq) ProtoMessage()               {}
func (*InfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InfoReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type InfoRes struct {
	Chats   []*Chat    `protobuf:"bytes,1,rep,name=chats" json:"chats,omitempty"`
	Message []*Message `protobuf:"bytes,2,rep,name=message" json:"message,omitempty"`
}

func (m *InfoRes) Reset()                    { *m = InfoRes{} }
func (m *InfoRes) String() string            { return proto1.CompactTextString(m) }
func (*InfoRes) ProtoMessage()               {}
func (*InfoRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InfoRes) GetChats() []*Chat {
	if m != nil {
		return m.Chats
	}
	return nil
}

func (m *InfoRes) GetMessage() []*Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type CreateChatReq struct {
	Me         int64   `protobuf:"varint,1,opt,name=me" json:"me,omitempty"`
	ChatterIds []int64 `protobuf:"varint,2,rep,packed,name=chatter_ids,json=chatterIds" json:"chatter_ids,omitempty"`
}

func (m *CreateChatReq) Reset()                    { *m = CreateChatReq{} }
func (m *CreateChatReq) String() string            { return proto1.CompactTextString(m) }
func (*CreateChatReq) ProtoMessage()               {}
func (*CreateChatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateChatReq) GetMe() int64 {
	if m != nil {
		return m.Me
	}
	return 0
}

func (m *CreateChatReq) GetChatterIds() []int64 {
	if m != nil {
		return m.ChatterIds
	}
	return nil
}

type CreateChatRes struct {
	ChatId        int64   `protobuf:"varint,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	CreaterUserId int64   `protobuf:"varint,2,opt,name=creater_user_id,json=createrUserId" json:"creater_user_id,omitempty"`
	ChatterIds    []int64 `protobuf:"varint,3,rep,packed,name=chatter_ids,json=chatterIds" json:"chatter_ids,omitempty"`
}

func (m *CreateChatRes) Reset()                    { *m = CreateChatRes{} }
func (m *CreateChatRes) String() string            { return proto1.CompactTextString(m) }
func (*CreateChatRes) ProtoMessage()               {}
func (*CreateChatRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateChatRes) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *CreateChatRes) GetCreaterUserId() int64 {
	if m != nil {
		return m.CreaterUserId
	}
	return 0
}

func (m *CreateChatRes) GetChatterIds() []int64 {
	if m != nil {
		return m.ChatterIds
	}
	return nil
}

type SendMessageReq struct {
	Me     int64  `protobuf:"varint,1,opt,name=me" json:"me,omitempty"`
	ChatId int64  `protobuf:"varint,2,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Body   string `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
}

func (m *SendMessageReq) Reset()                    { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string            { return proto1.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()               {}
func (*SendMessageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SendMessageReq) GetMe() int64 {
	if m != nil {
		return m.Me
	}
	return 0
}

func (m *SendMessageReq) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *SendMessageReq) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type SendMessageRes struct {
}

func (m *SendMessageRes) Reset()                    { *m = SendMessageRes{} }
func (m *SendMessageRes) String() string            { return proto1.CompactTextString(m) }
func (*SendMessageRes) ProtoMessage()               {}
func (*SendMessageRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Chatter struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *Chatter) Reset()                    { *m = Chatter{} }
func (m *Chatter) String() string            { return proto1.CompactTextString(m) }
func (*Chatter) ProtoMessage()               {}
func (*Chatter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Chatter) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Chat struct {
	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
}

func (m *Chat) Reset()                    { *m = Chat{} }
func (m *Chat) String() string            { return proto1.CompactTextString(m) }
func (*Chat) ProtoMessage()               {}
func (*Chat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Chat) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

type Message struct {
	Sender int64  `protobuf:"varint,1,opt,name=sender" json:"sender,omitempty"`
	Chat   *Chat  `protobuf:"bytes,2,opt,name=chat" json:"chat,omitempty"`
	Body   string `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto1.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Message) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *Message) GetChat() *Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto1.RegisterType((*InfoReq)(nil), "proto.InfoReq")
	proto1.RegisterType((*InfoRes)(nil), "proto.InfoRes")
	proto1.RegisterType((*CreateChatReq)(nil), "proto.CreateChatReq")
	proto1.RegisterType((*CreateChatRes)(nil), "proto.CreateChatRes")
	proto1.RegisterType((*SendMessageReq)(nil), "proto.SendMessageReq")
	proto1.RegisterType((*SendMessageRes)(nil), "proto.SendMessageRes")
	proto1.RegisterType((*Chatter)(nil), "proto.Chatter")
	proto1.RegisterType((*Chat)(nil), "proto.Chat")
	proto1.RegisterType((*Message)(nil), "proto.Message")
}

func init() { proto1.RegisterFile("proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x6e, 0x83, 0x30,
	0x10, 0x86, 0x15, 0x48, 0xa0, 0x39, 0x14, 0x5a, 0x79, 0x68, 0x91, 0x3a, 0x90, 0x7a, 0x88, 0x98,
	0x32, 0xb4, 0x2f, 0x50, 0x89, 0x89, 0x21, 0x1d, 0x5c, 0xb5, 0x2b, 0x72, 0xe2, 0x6b, 0xc3, 0x00,
	0x14, 0x9b, 0x0c, 0x7d, 0xfb, 0xca, 0x87, 0x91, 0x1a, 0x9a, 0x2e, 0x09, 0xbe, 0xfb, 0xf8, 0xee,
	0x3f, 0x0c, 0xd1, 0x97, 0x6e, 0xfb, 0x76, 0x4b, 0xbf, 0x6c, 0x41, 0x7f, 0x7c, 0x03, 0x61, 0xd1,
	0x7c, 0xb4, 0x02, 0x3b, 0x76, 0x0f, 0xcb, 0x93, 0x41, 0x5d, 0x36, 0xb2, 0xc6, 0x64, 0xb6, 0x9e,
	0x65, 0x4b, 0x71, 0x65, 0x0b, 0x2f, 0xb2, 0x46, 0xfe, 0x3e, 0x72, 0x86, 0x3d, 0xc0, 0xe2, 0x70,
	0x94, 0xbd, 0x49, 0x66, 0x6b, 0x3f, 0x8b, 0x1e, 0xa3, 0x41, 0xb8, 0xcd, 0x8f, 0xb2, 0x17, 0x43,
	0x87, 0x65, 0x10, 0xd6, 0x68, 0x8c, 0xfc, 0xc4, 0xc4, 0x23, 0x28, 0x76, 0xd0, 0x6e, 0xa8, 0x8a,
	0xb1, 0xcd, 0x9f, 0x61, 0x95, 0x6b, 0x94, 0x3d, 0xd2, 0xeb, 0xd8, 0xb1, 0x18, 0x3c, 0x37, 0xde,
	0x17, 0x5e, 0x8d, 0x2c, 0x85, 0xc8, 0x3a, 0x7b, 0xd4, 0x65, 0xa5, 0x0c, 0xe9, 0x7c, 0x01, 0xae,
	0x54, 0x28, 0xc3, 0xbb, 0x73, 0x83, 0x61, 0x77, 0x10, 0xda, 0x76, 0x59, 0x29, 0xa7, 0x09, 0xec,
	0xb1, 0x50, 0x6c, 0x03, 0xd7, 0x07, 0x22, 0x75, 0x49, 0x8b, 0x56, 0x2a, 0xf1, 0x08, 0x58, 0xb9,
	0xf2, 0x9b, 0xb1, 0xca, 0xe9, 0x48, 0xff, 0xcf, 0xc8, 0x1d, 0xc4, 0xaf, 0xd8, 0xa8, 0x71, 0x99,
	0x0b, 0xa9, 0x7f, 0x65, 0xf0, 0xce, 0x32, 0x30, 0x98, 0xef, 0x5b, 0xf5, 0x9d, 0xf8, 0xf4, 0x7d,
	0xe9, 0x99, 0xdf, 0x4c, 0x74, 0x86, 0x73, 0x08, 0xf3, 0x61, 0x9c, 0x35, 0x8d, 0x61, 0xdd, 0x36,
	0x27, 0x4a, 0xc9, 0x53, 0x98, 0x5b, 0xe6, 0xdf, 0x75, 0xed, 0x95, 0x39, 0x25, 0xbb, 0x85, 0xc0,
	0x60, 0xa3, 0x50, 0x8f, 0xc8, 0x70, 0x62, 0x29, 0xcc, 0x2d, 0x4c, 0x19, 0x27, 0x37, 0x49, 0x8d,
	0x4b, 0x71, 0xf7, 0x01, 0x51, 0x4f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x17, 0xad, 0x5a, 0x0f,
	0x4f, 0x02, 0x00, 0x00,
}
